columnSuffix: null
contentColumnType: string
fieldGroup: 03a7a629-c5be-46eb-997b-ba51a4f55731 # Common
handle: featureImage
instructions: ''
name: 'Feature Image'
searchable: true
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:d6947288-b758-4a87-91a7-83c13bcd9329' # Uploads
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Add Feature Image'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:d6947288-b758-4a87-91a7-83c13bcd9329' # Uploads
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:d6947288-b758-4a87-91a7-83c13bcd9329' # Uploads
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
