columnSuffix: null
contentColumnType: string
fieldGroup: 03a7a629-c5be-46eb-997b-ba51a4f55731 # Common
handle: navigation
instructions: ''
name: Navigation
searchable: true
settings:
  contentTable: '{{%matrixcontent_navigation}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
