defaultPlacement: end
enableVersioning: true
handle: blogPosts
name: 'Blog Posts'
propagationMethod: all
siteSettings:
  6ffb3c87-a384-463e-aaed-202be5098a93: # Craft Demo
    enabledByDefault: true
    hasUrls: true
    template: blog\_entry
    uriFormat: 'blog/{slug}'
type: channel
