defaultPlacement: end
enableVersioning: true
handle: blog
name: Blog
propagationMethod: all
siteSettings:
  6ffb3c87-a384-463e-aaed-202be5098a93: # Craft Demo
    enabledByDefault: true
    hasUrls: true
    template: blog\index
    uriFormat: blog
type: single
